### ISSUE TITLE
Docker 18.09 can't be installed

### ISSUE THREAD

**Issue by mfortin** [chef-cookbooks/docker#1036]
### Cookbook version
4.6.7

### Chef-client version
12.21.3

### Platform Details
CentOS 7.5

### Scenario:
Install docker 18.09

### Steps to Reproduce:
set version to 18.09

### Expected Result:
Docker 18.09 installed

### Actual Result:
Version ["18.09.0.ce-3.el7"] of ["docker-ce"] not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)

**Comment by isuftin** [comment]
It looks like this is due to the version + release being changed from 18.03.1

```
Name        : docker-ce
Arch        : x86_64
Version     : 18.03.1.ce
Release     : 1.el7.centos
```

vs

```
Name        : docker-ce
Arch        : x86_64
Epoch       : 3
Version     : 18.09.0
Release     : 3.el7
Size        : 19 M
``` 

It looks like they also removed the `.centos` from the tail end of the Release :/

**Comment by isuftin** [comment]
So it would seem like something here would have to change: https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_installation_package.rb#L155

**Comment by isuftin** [comment]
Actually, my bad. Here: https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_installation_package.rb#L160

**Comment by isuftin** [comment]
@mfortin For now, you can change "version" to "package_version" in your service definition.

Example:

```
      "service" : {
        "default" : {
          "package_version": "18.09.0-3.el7",
          "install_method": "package",
          "storage_driver": "overlay2",
          "storage_opts": [
            "overlay2.override_kernel_check=true"
          ]
        }
      }
```

This works for me for CentOS 7. However, I do see this issue in the logs:

`* yum_package[docker-ce] action install[2018-11-28T20:01:42+00:00] WARN: yum_package[docker-ce] docker-ce has installed version 3:18.09.0-3.el7.x86_64, which is newer than available version 18.09.0-3.el7. Skipping...)`

Up to you whether or not that's going to bother you until a fixed version of the cookbook comes out ;)

**Comment by tas50** [comment]
This is resolved on master thanks to @smcavallo's PR

**Comment by ChrisG1971** [comment]
This version has not been loaded to the supermarket yet @tas50

**Comment by ChrisG1971** [comment]
@tas50  Has anyone else been successful with this latest version.   I am still getting the same error trying to pass the package_version and it's telling me to pass version-release.  The version being referenced is not even the same version I'm specifying in the package_version.

**Comment by isuftin** [comment]
@ChrisG1971 I just tested the latest version. I am not using package_version anymore though. I've just switched back to using `version` and am using `18.09.0` and it works as expected

```
"service" : {
        "default" : {
          "version": "18.09.0",
          "install_method": "package",
          "storage_driver": "overlay2",
          "storage_opts": [
            "overlay2.override_kernel_check=true"
          ]
        }
      }
```

👍
