### ISSUE TITLE
Compile fail with docker_service when specifying install_method 'binary' and 'version'

### ISSUE THREAD

**Issue by jmccann** [chef-cookbooks/docker#640]
Given
```ruby
docker_service 'default' do
  version '1.9.1'
  install_method 'binary'
end
```

I receive
```
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/tgt-drone/recipes/default.rb
       ================================================================================
       
       Chef::Exceptions::ValidationFailed
       ----------------------------------
       Version property only supported for binary and package installation methods

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb:34:in `coerce_version'
         /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb:27:in `block in <class:DockerService>'
         /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:624:in `instance_exec'
         /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:624:in `exec_in_resource'
         /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:446:in `coerce'
         /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:652:in `coerce_and_validate'
         /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:634:in `input_to_stored_value'
         /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:391:in `set'
         /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:291:in `call'
         /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:514:in `version'
         /tmp/kitchen/cache/cookbooks/tgt-drone/recipes/default.rb:14:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/tgt-drone/recipes/default.rb:13:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb:
       
        27:      property :version, String, coerce: proc { |v| coerce_version(v) }, desired_state: false
        28:  
        29:      ################
        30:      # Helper Methods
        31:      ################
        32:      def coerce_version(v)
        33:        if (v && (install_method != 'binary')) || (v && (install_method != 'package'))
        34>>         raise Chef::Exceptions::ValidationFailed, 'Version property only supported for binary and package installation methods'
        35:        end
        36:      end
        37:  
        38:      def copy_properties_to(to, *properties)
        39:        properties = self.class.properties.keys if properties.empty?
        40:        properties.each do |p|
        41:          # If the property is set on from, and exists on to, set the
        42:          # property on to
        43:          if to.class.properties.include?(p) && property_is_set?(p)
 
```

This was working fine `< 2.4.16`

**Comment by someara** [comment]
investigating

**Comment by someara** [comment]
I used a different technique in 2.4.18. It should be fixed up now.
Closing here. Let me know if that didn't work

**Comment by jmccann** [comment]
@someara It seems I'm still having issues, just later in the process

Given
```ruby
docker_service 'default' do
  version '1.9.1'
  install_method 'binary'
end
```

I now get
```
       Recipe: test-docker::default
         * docker_service[default] action create
           
           ================================================================================
           Error executing action `create` on resource 'docker_service[default]'
           ================================================================================
           
           Chef::Exceptions::ValidationFailed
           ----------------------------------
           Version property only supported for binary and package installation methods
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb:36:in `validate_install_method'
           /tmp/kitchen/cache/cookbooks/docker/libraries/docker_service.rb:93:in `block in <class:DockerService>'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/test-docker/recipes/default.rb
           
             7: docker_service 'default' do
             8:   version '1.9.1'
         9:   install_method 'binary'
            10: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/test-docker/recipes/default.rb:7:in `from_file'
           
           docker_service("default") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :docker_service
         cookbook_name "test-docker"
             recipe_name "default"
             version "1.9.1"
             install_method "binary"
       end
```

**Comment by someara** [comment]
Ug. I've disabled the validation check in 2.4.20.
I'll revisit this later.

**Comment by jmccann** [comment]
@someara OK, it's working now.  :stuck_out_tongue: 

Thanks!
