### ISSUE TITLE
crash on 12.16.x chef-client run

### ISSUE THREAD

**Issue by AVVS** [chef-cookbooks/docker#779]
### Cookbook version

`2.9.10`

### Chef-client version

```
Starting Chef Client, version 12.16.42
resolving cookbooks for run list: ["cappasity-core::ms-users"]
Synchronizing Cookbooks:
  - cappasity-core (0.5.2)
  - cappasity-docker (0.3.4)
  - docker (2.9.10) <---
  - chef-sugar (3.4.0)
  - compat_resource (12.16.2)
  - chef-vault (1.3.2)
  - chef-apt-docker (1.0.0)
  - sysctl (0.8.1)
  - ohai (4.2.2)
  - cron (3.0.0)
```

### Platform Details

`ubuntu 14.04, GCE`

### Scenario:

```
sudo chef-client
settings on docker daemon change, crash
```

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:

```
      * template[/etc/default/docker] action create
      - update content in file /etc/default/docker from c9e1ca to 3165d0
      --- /etc/default/docker	2016-09-14 14:04:39.016176312 +0000
      +++ /etc/default/.chef-docker20161129-12781-1dw23cx	2016-11-29 10:58:45.961101969 +0000
      @@ -4,7 +4,7 @@
       DOCKER="/usr/bin/dockerd"
       
       # Use DOCKER_OPTS to modify the daemon startup options.
      -DOCKER_OPTS="--bip=172.17.42.1/16 --dns=172.17.42.1 --dns-search=service.consul --graph=/var/lib/ms-users/docker-data -H unix:///var/run/docker.sock -H tcp://10.240.0.16:2376 --pidfile=/var/run/docker.pid --storage-driver=overlay2 --tlsverify=true --tlscacert=/etc/docker/tls_ca_cert.pem --tlscert=/etc/docker/tls_server_cert.pem --tlskey=/etc/docker/tls_server_key.pem"
      +DOCKER_OPTS="--bip=172.17.42.1/16 --dns=172.17.42.1 --dns-search=service.consul --dns-search=c.redacted.internal --dns-search=google.internal --graph=/var/lib/ms-users/docker-data -H unix:///var/run/docker.sock -H tcp://10.240.0.16:2376 --pidfile=/var/run/docker.pid --storage-driver=overlay2 --tlsverify=true --tlscacert=/etc/docker/tls_ca_cert.pem --tlscert=/etc/docker/tls_server_cert.pem --tlskey=/etc/docker/tls_server_key.pem"
       
       # If you need Docker to use an HTTP proxy, it can also be specified here.
       
    * docker_service_manager_upstart[default] action restart
      * service[docker] action stop
        - stop service service[docker]
      * directory[/usr/lib/docker] action create (up to date)
      * template[/usr/lib/docker/docker-wait-ready] action create (up to date)
      * template[/etc/init/docker.conf] action create (up to date)
      * template[/etc/default/docker] action create (up to date)
      * service[docker] action start
        - start service service[docker]
    
    * service[docker] action start (up to date)
  
  
  ================================================================================
  Error executing action `start` on resource 'docker_service_manager_upstart[default]'
  ================================================================================
  
  NoMethodError
  -------------
  undefined method `updated' for nil:NilClass
  
  Resource Declaration:
  ---------------------
  # In /var/chef/cache/cookbooks/cappasity-docker/recipes/engine.rb
  
   31: docker_service_manager 'default' do
   32:   host ['unix:///var/run/docker.sock', "tcp://#{node[:ipaddress]}:2376"]
   33:   tls_verify true
   34: 
   35:   # Apply tls options
   36:   node['docker']['tls_options'].each do |opt|
   37:     self.send opt, "/etc/docker/#{opt}.pem"
   38:   end
   39: 
   40:   storage_driver node['docker']['storage_driver']
   41:   graph node['docker']['data_dir']
   42: 
   43:   bip "#{node[:docker][:bip]}/16"
   44:   dns [node[:docker][:bip]]
   45:   dns_search ['service.consul', "c.#{node[:google_project]}.internal", 'google.internal']
   46: 
   47:   action :start
   48: end
   49: 
  
  Compiled Resource:
  ------------------
  # Declared in /var/chef/cache/cookbooks/cappasity-docker/recipes/engine.rb:31:in `from_file'
  
  docker_service_manager_upstart("default") do
    action [:start]
    updated true
    updated_by_last_action true
    retries 0
    retry_delay 2
    default_guard_interpreter :default
    declared_type :docker_service_manager
    cookbook_name "cappasity-docker"
    recipe_name "engine"
    host ["unix:///var/run/docker.sock", "tcp://10.240.0.16:2376"]
    tls_verify true
    tls_ca_cert "/etc/docker/tls_ca_cert.pem"
    tls_client_cert "/etc/docker/tls_client_cert.pem"
    tls_client_key "/etc/docker/tls_client_key.pem"
    tls_server_cert "/etc/docker/tls_server_cert.pem"
    tls_server_key "/etc/docker/tls_server_key.pem"
    storage_driver ["overlay2"]
    graph "/var/lib/ms-users/docker-data"
    bip "172.17.42.1/16"
    dns ["172.17.42.1"]
    dns_search ["service.consul", "c.redacted.internal", "google.internal"]
    pidfile "/var/run/docker.pid"
  end
  
  Platform:
  ---------
  x86_64-linux

```

**Comment by someara** [comment]
This should be fixed already. Upgrade to the current version?

**Comment by AVVS** [comment]
Hm, I think I did miss the updates. Thx and sorry

**Comment by popsikle** [comment]
This is still happening, chef client 12.16.42, cookbook version 2.15.8
